### ISSUE TITLE
How did you decide which data from the Entrez Gene site to include within hetio?

### ISSUE THREAD

**Issue by krishbharat96** [dhimmel/entrez-gene#1]
I am currently scripting auto-update scripts for hetio and I am currently working on the Gene nodes, So, I was looking at the `process.ipynb` file, and I was wondering how exactly you decided which of the 56532 gene entries from the NCBI website got input into hetio. I realized that you got rid of any gene that was not a Homo sapiens gene and I am guessing you got rid of any gene that is not "protein-coding." However, I did notice a few genes within the SPOKE network (for instance: LOC102725191) that are not protein-coding genes, and I was wondering how exactly you decided which ones went into the network from the Entrez Gene database.

**Comment by dhimmel** [comment]
> However, I did notice a few genes within the SPOKE network

I believe by SPOKE you're referring to Hetionet v1.0? Note that "hetio" usually refers to the Python package [`hetio`](https://github.com/dhimmel/hetio) or the website http://het.io. In the past, we've referred to the network as Hetionet. Of course, I'm excited that you are continuing work enhancing the network in [`krishbharat96/SPOKE_Integration`](https://github.com/krishbharat96/SPOKE_Integration). For disambiguation, we should refer to the existing network published in https://doi.org/10.7554/eLife.26726 as Hetionet v1.0 and your enhanced version as SPOKE.

Indeed, _LOC102725191_ is in Hetionet v1.0. I confirmed this with the following query at https://neo4j.het.io/browser/

```cypher
MATCH (gene:Gene)
WHERE gene.name = 'LOC102725191'
RETURN gene
```

> how exactly you decided which ones went into the network from the Entrez Gene database

[`process.ipynb`](https://github.com/dhimmel/entrez-gene/blob/a7362748a34211e5df6f2d185bb3246279760546/process.ipynb) performs the species filter:

```python
gene_df = gene_df.query('tax_id == 9606')
```

In `dhimmel/integrate`, the notebook [`integrate.ipynb`](https://github.com/dhimmel/integrate/blob/93feba1765fbcd76fd79e22f25121f5399629148/integrate.ipynb) further filters for `protein-coding` genes:

```python
gene_df = gene_df[gene_df.type_of_gene == 'protein-coding']
```

My guess is that [_LOC102725191_](https://www.ncbi.nlm.nih.gov/gene/102725191) used to be typed as protein-coding in Entrez Gene, but this has subsequently been fixed.

If you're looking to update the catalog of genes, I'd recommend using the pipeline from [`cognoma/genes`](https://github.com/cognoma/genes). You could rerun that code with the latest Entrez Gene data. One nice thing about the `cognoma/genes` repository is that it creates [`updater.tsv`](https://github.com/cognoma/genes/blob/721204091a96e55de6dcad165d6d8265e67e2a48/data/updater.tsv), which will allow you to update outdated gene IDs rather than just ignore them.

Does that answer things?

**Comment by krishbharat96** [comment]
Hi Daniel,
That really helped. Thank you for the answer! I did not realize the distinction in naming terminologies: thanks for that. And, yes I am very excited to be working on this network. It seems to have real potential for the future.

**Comment by dhimmel** [comment]
@krishbharat96 sounds good. Happy to provide advice via GitHub Issues in the relevant repositories!
